# development:
#   adapter: async
#
# test:
#   adapter: async
#
# production:
#   adapter: redis
#   ur: redis-url
#   channel_prefix: manager_production

redis: &redis
  adapter: redis
  url: <%= ENV['ACTION_CABLE_REDIS_HOST'] %>
production: *redis
development: *redis
uat: *redis
staging: *redis
test:
  url: redis://localhost:6379/1
