# development:
#   adapter: async
#
# test:
#   adapter: async
#
# production:
#   adapter: redis
#   ur: redis-url
#   channel_prefix: manager_production

redis: &redis
  adapter: redis
  url: redis://localhost:6379/3

production: *redis
development: *redis
test: *redis
